((nil . ((indent-tabs-mode . t)))
 (c-mode . ((c-file-style . "linux")
            (indent-tabs-mode . t)
            (tab-width . 8)))
 (cc-mode . ((c-file-style . "linux")
            (indent-tabs-mode . t)
            (tab-width . 8)))
 (perl-mode . ((perl-indent-level . 2)
               (perl-continued-statement-offset . 2)
               (perl-continued-brace-offset . 0)
               (perl-brace-offset . 0)
               (perl-brace-imaginary-offset . 0)
               (perl-label-offset . -2)
               (indent-tabs-mode . nil)
               (tab-width . 2)))
 (cperl-mode . ((perl-indent-level . 2)
               (perl-continued-statement-offset . 2)
               (perl-continued-brace-offset . 0)
               (perl-brace-offset . 0)
               (perl-brace-imaginary-offset . 0)
               (perl-label-offset . -2)
               (indent-tabs-mode . nil)
               (tab-width . 2))))
