language: c
sudo: required
dist: trusty
script: cd src/guests/simple_busybox/ && sudo ./build.pl --build-ompi --build-kernel --build-busybox --build-dropbear --build-libhugetlbfs --build-numactl --build-hwloc --build-pisces --build-image --build-isoimage && ../../../ci/run_tests.sh
compiler:
- gcc-4.8
before_install: ci/before_install.sh
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - mtools
    - genisoimage
    - syslinux
    - qemu
    - live-image-rescue
    - libdevel-trace-perl
notifications:
    - hobbes-virt@elist.ornl.gov
    - noah.evans@gmail.com
    - ktpedre@sandia.gov

