language: c
script: cd src/guests/simple_busybox/ && sudo ./build.pl --build-ompi --build-kernel --build-busybox --build-dropbear --build-libhugetlbfs --build-numactl --build-hwloc   --build-pisces --build-image --build-isoimage
compiler:
- gcc-4.8
addons:
  apt:
    packages:
    - gcc-4.8