# Makefile for the kernel cdrom device drivers.
#
# 30 Jan 1998, Michael Elizabeth Chastain, <mailto:mec@shout.net>
# Rewritten to use lists instead of if-statements.

# Each configuration option enables a list of files.

obj-$(CONFIG_KGNI))	+=              kgni_main.o
ccflags-y := -I.

kgni-y       := kgni_main.o 




obj-$(CONFIG_KGNI)       += kgni_main.o

